import SignUpForm from '@/components/auth/sign-up-form'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Debate Io | Sign Up",
    description: "Generated by create next app",
};
export default function SignUp() {
    return (
        <SignUpForm />
    )
}
