import type { Metadata } from "next";
import { montserrat400 } from "@/fonts/custom/montserrat";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemProvider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/appSidebar";

export const metadata: Metadata = {
  title: "Debate Io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat400.className} min-h-screen antialiased flex items-center justify-center`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          forcedTheme="dark"
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <main className="p-4">
              <SidebarTrigger />
              <section className="w-full h-full p-10 flex items-start justify-center">
                {children}
              </section>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
