import type { Metadata } from "next";
import { montserrat400 } from "@/fonts/custom/montserrat";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemProvider";

export const metadata: Metadata = {
  title: "Debate Io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat400.className} min-h-screen relative antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          forcedTheme="dark"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
