import SignInForm from '@/components/auth/sign-in-form';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Debate Io | Sign In",
    description: "Generated by create next app",
};
export default function SignIn() {
    return (
        <SignInForm />
    )
}
