import { AppSidebar } from '@/components/appSidebar'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Debate Io",
    description: "Generated by create next app",
};

export default function ProtectedLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="min-h-screen relative flex items-center justify-center">
            <SidebarProvider>
                <AppSidebar />
                <main className="p-4 w-screen min-h-screen">
                    <SidebarTrigger />
                    <section className="w-full h-full p-10 flex items-center justify-center">
                        {children}
                    </section>
                </main>
            </SidebarProvider>
        </main>
    )
}
